config/routes.rb
Rails.application.routes.draw do
  root 'tickets#index'
  
  resources :clients do
  	resources :people
    resources :fleets
  end

  post 'disabled_client', to: 'clients#disabled', as: 'disabled_client'
  get 'clients/:client_id/people/:id/disable', to: 'people#disable'

  resources :users
  get 'users/:id/disable', to: 'users#disable'
  resources :sessions, only: [:new, :create, :destroy]
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :tickets do
    
    resources :ticket_answers
    # member do
    #   post '/tickets/close_ticket', to: 'tickets#close_ticket', as: 'close_ticket'
    # end
  end

  get 'tickets/get_tickets/:ticket_status_id', to: 'tickets#get_tickets', as: 'get_tickets'
  get 'count_tickets', to: 'tickets#count_tickets', as: 'count_tickets'
  get 'get_fleet/:client_id/:fleet_type_id', to: 'fleets#get_fleet', as: 'get_fleet'
  post 'assign_person', to: 'tickets#assign_person', as: 'assign_person'
  post 'close_ticket', to: 'tickets#close_ticket', as: 'close_ticket'

  # Reports
  resources :reports, only: [:index]
  get 'report_between_dates/:start_date/:end_date', to: 'reports#report_between_dates', as: 'report_between_dates', defaults: { format: 'xlsx' }

end

app/models/person.rb
class Person < ApplicationRecord
  belongs_to :client
  belongs_to :person_type
  has_many :tickets
  has_many :fleets
  # has_many :assigned_tickets, :class_name => 'Ticket', :foreign_key => 'assigned_to' 
  # has_one :user
	validates :name, presence: true,
						length: { minimum: 3 }
	validates :person_type, presence: true
end

app/models/person_type.rb
class PersonType < ApplicationRecord
	has_many :people
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy, :disable]

  # GET /people
  # GET /people.json
  def index
    @title = 'Personas'
    @client = Client.find(params[:client_id])
    @people = Person.where(client_id: params[:client_id], active: true)
    respond_to do |format|
      format.html
      format.json
    end
  end

  # GET /people/1
  # GET /people/1.json
  def show
    @client = Client.find(params[:client_id])
    @person = Person.find(params[:id])
    respond_to do |format|
      format.js
    end
  end

  def get_for_client
    @person = Person.find(params[:client_id])
    respond_to do |format|
      format.json
    end
  end

  # GET /people/new
  def new
    @client = Client.find(params[:client_id])
    @person_types = PersonType.where(active: :true).order(name: :asc)
    respond_to do |format|
      format.js
    end
  end

  # GET /people/1/edit
  def edit
    @client = Client.find(params[:client_id])
    @person_types = PersonType.where(active: :true).order(name: :asc)
    respond_to do |format|
      format.js
    end
  end

  # POST /people
  # POST /people.json
  def create
    @client = Client.find(params[:client_id])
    @person = @client.people.create(person_params)

    respond_to do |format|
      if @person.save
        format.js
        format.json { render json: {status: 'success'}, status: :created }
      else
        format.js
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end


  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        @alert = { 'type' => 'success', 'msg' => 'Persona actualizada con éxito!' }
        format.json { render json: { status: 'success' } , status: :created }
      else
        @alert = { 'type' => 'error', 'msg' => 'Ocurrio un error: no se pudieron actualizar los datos.' }
        format.html { render :edit }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.update(active: false)
    respond_to do |format|
      format.html { redirect_to people_url, notice: 'Person was successfully destroyed.' }
      # format.json { head :no_content }
      format.json { render status: ok }
    end
  end

  def disable
    respond_to do |format|
      if @person.update(active: false)
        format.json { render json: { status: :success }, status: :ok }
      else
        format.json { render json: 'error', status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def person_params
      params.require(:person).permit(:person_type_id, :name, :surname, :dni, :email, :phone, :active, :client_id, :send_email)
    end
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/people/_form.html.erb
<div class="modal-dialog" role="document">
  <div class="modal-content">
    <div class="modal-header">
      <h5 class="modal-title">Alta de persona</h5>
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <div class="modal-body">
      <%= form_with(model: [ @client, @client.people.build ], :id => 'form-new-person', class: 'g-brd-around g-brd-gray-light-v4 g-pa-30 g-mb-30', 
            data: { type: "json" } ) do |form| %>
        <div id="error_explanation" class="alert alert-danger" style="display:none">
          <ul id="error_list"></ul>
        </div>

        <div class="form-group row">
        <label for="client_type_client_id" class="col-sm-3 col-form-label">Tipo persona</label>
        <div class="col-sm-6">
          <select class="form-control" id="person_person_type_id" name="person[person_type_id]" class="form-control">
            <option disabled selected>Seleccione tipo de persona</option>
            <% @person_types.each do |t|  %>
              <option value="<%= t.id %>"><%= t.name %></option>
            <% end %>
          </select>
        </div>
      </div>

      <div class="form-group row">
        <%= form.label :name,'Nombre', class: 'col-sm-3 col-form-label' %>
        <div class="col-9">
          <%= form.text_field :name, class: 'form-control rounded-0' %>
        </div>
      </div>

      <div class="form-group row">
        <%= form.label :surname,'Apellido', class: 'col-sm-3 col-form-label' %>
        <div class="col-9">
          <%= form.text_field :surname, class: 'form-control rounded-0' %>
        </div>
      </div>

      <div class="form-group row">
        <%= form.label :dni,'DNI', class: 'col-sm-3 col-form-label' %>
        <div class="col-9">
          <%= form.text_field :dni, class: 'form-control rounded-0' %>
        </div>
      </div>

      <div class="form-group row">
        <%= form.label :email,'Email', class: 'col-sm-3 col-form-label' %>
        <div class="col-9">
          <%= form.text_field :email, class: 'form-control rounded-0' %>
        </div>
      </div>

      <div class="form-group row">
        <%= form.label :phone,'Telefono', class: 'col-sm-3 col-form-label' %>
        <div class="col-9">
          <%= form.text_field :phone, class: 'form-control rounded-0' %>
        </div>
      </div>

      <div class="actions">
        <%= form.submit 'Agregar', class: 'btn btn-primary' %>
        <button type="button" class="btn btn-danger" data-dismiss="modal">Cerrar</button>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/people/_form_edit.html.erb
<div class="modal-dialog" role="document">
  <div class="modal-content">
    <div class="modal-header">
      <h5 class="modal-title">Editar cliente</h5>
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <div class="modal-body">
      <%= form_with(model: [@client, @person], remote: true, :html => { :id => 'form-edit-person' } ) do |form| %>

      <div id="error_explanation" class="alert alert-danger" style="display:none">
        <ul id="error_list"></ul>
      </div>

      <div class="form-group row">
        <label for="person_person_type_id" class="col-sm-3 col-form-label">Tipo persona</label>
        <div class="col-sm-6">
          <select class="form-control" id="person_person_type_id" name="person[person_type_id]" class="form-control">
            <option disabled selected value="">Seleccione tipo de cliente</option>
            <% @person_types.each do |t|  %>
              <% if !@person.nil? && @person.person_type_id == t.id %>
                <option value="<%= t.id %>" selected ><%= t.name %></option>
                <% else %>
                <option value="<%= t.id %>"><%= t.name %></option>
              <% end %>
            <% end %>
          </select>
        </div>
      </div>

      <div class="form-group row">
        <%= form.label :name,'Nombre', class: 'col-sm-3 col-form-label' %>
        <div class="col-9">
          <%= form.text_field :name, class: 'form-control rounded-0' %>
        </div>
      </div>

      <div class="form-group row">
        <%= form.label :surname,'Apellido', class: 'col-sm-3 col-form-label' %>
        <div class="col-9">
          <%= form.text_field :surname, class: 'form-control rounded-0' %>
        </div>
      </div>

      <div class="form-group row">
        <%= form.label :dni,'DNI', class: 'col-sm-3 col-form-label' %>
        <div class="col-9">
          <%= form.text_field :dni, class: 'form-control rounded-0' %>
        </div>
      </div>

      <div class="form-group row">
        <%= form.label :email,'Email', class: 'col-sm-3 col-form-label' %>
        <div class="col-9">
          <%= form.text_field :email, class: 'form-control rounded-0' %>
        </div>
      </div>

      <div class="form-group row">
        <%= form.label :phone,'Telefono', class: 'col-sm-3 col-form-label' %>
        <div class="col-9">
          <%= form.text_field :phone, class: 'form-control rounded-0' %>
        </div>
      </div>

      <div class="actions">
        <%= form.submit 'Agregar', class: 'btn btn-primary' %>
        <button type="button" class="btn btn-danger" data-dismiss="modal">Cerrar</button>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/people/_show.html.erb
<div class="modal-dialog" role="document">
  <div class="modal-content">
    <div class="modal-header">
      <h5 class="modal-title">Datos de la persona</h5>
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <div class="modal-body">
      <p>
        <strong>Cliente:</strong>
        <%= @person.client.name %>
      </p>
      <p>
        <strong>Tipo:</strong>
        <%= @person.type_person %>
      </p>

      <p>
        <strong>Nombre: </strong>
        <%= @person.name %> <%= @person.surname %>
      </p>



      <p>
        <strong>DNI:</strong>
        <%= @person.dni %>
      </p>

      <p>
        <strong>Email:</strong>
        <%= @person.email %>
      </p>

      <p>
        <strong>Cel:</strong>
        <%= @person.phone %>
      </p>


      <button type="button" class="btn btn-danger" data-dismiss="modal">Cerrar</button>
    </div>
  </div>
</div>

app/views/people/_text.html.erb
<p>test</p>

app/views/people/create.js.erb
  persons_table.ajax.reload(null,false)
  $('#modal-person').modal('hide')

app/views/people/edit.html.erb
<h1>Editing Person</h1>

<%= render 'form_edit', person: @person %>

<%= link_to 'Show', client_person_path(@person) %> |
<%= link_to 'Back', client_persons_path %>

app/views/people/edit.js.erb
$("#modal-person").html("<%= j (render 'form_edit') %>")
$("#modal-person").modal('show')

var form_edit_person = $('#form-edit-person').validate({
	rules: {
		'person[person_type_id]': {
			required: true,
			// Using the normalizer to trim the value of the element
			// before validating it.
			//
			// The value of `this` inside the `normalizer` is the corresponding
			// DOMElement. In this example, `this` references the `username` element.
			normalizer: function(value) {
				return $.trim(value);
			}
		},
		'person[name]': {
			required: true
		},
		'person[type_client]': {
			required: true
		},
		'person[dni]': {
			number: true
		},
		'person[phone]': {
			number: true
		}

	}
})


$("#form-edit-person").on("ajax:success", function(event) {
  people_table.ajax.reload(null,false)
  noty_alert('success', 'Edición exitosa')
  $("#modal-person").modal('hide')
}).on("ajax:error", function(event) {
	$('#form-edit-person #error_explanation').hide(500)
  $('#form-edit-person #error_list').empty()
	var msj = jQuery.parseJSON( event.detail[2].response )
	$.each( msj, function( key, value ) {
	  $('#form-edit-person #error_list').append('<li> ' + key + ": " + value + ' </li>')
	})
	$('#form-edit-person #error_explanation').show('slow')
})

app/views/people/index.html.erb
<div class="page-header card">
  <div class="row align-items-end">
    <div class="col-lg-8">
      <div class="page-header-title">
        <i class="ti-user bg-c-blue"></i>
        <div class="d-inline">
          <h5>Personal de <%= @client.name %></h5>
        <span>Descripcion de la vista</span>
        </div>
      </div>
    </div>
    <div class="col-lg-4">
      <div class="page-header-breadcrumb">
        <ul class=" breadcrumb breadcrumb-title">
          <li class="breadcrumb-item">
            <%= link_to '<i class="ti-home"></i>'.html_safe, root_path %>
          </li>
          <li class="breadcrumb-item">
            <%= link_to 'Clientes', clients_path %>
          </li>
          <li class="breadcrumb-item">
            <%= link_to 'Personal', client_people_path %>
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>

<div class="pcoded-inner-content">
  <div class="main-body">
    <div class="page-wrapper">
      <div class="page-body">
        <div class="card">
          <div class="card-header">
            <%= link_to 'Nueva persona', new_client_person_path, {:remote => true, 'data-toggle' =>  "modal",
                                                 'data-target' => '#modal-person', 'class' => 'btn btn-primary'} %>
          </div>
          <div class="card-block">
            <div class="table-responsive dt-responsive">
              <table id="people_table" class="table table-striped table-bordered nowrap w-100">
                <thead>
                  <tr>
                    <th>Nombre</th>
                    <th>Apellido</th>
                    <th>DNI</th>
                    <th>Email</th>
                    <th>Teléfono</th>
                    <th>Acciones</th>
                  </tr>
                </thead>
                 <tbody> <!-- Ajax --> </tbody> 
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- Modal para alta y edicion de persona -->
<div class="modal" id="modal-person" role="dialog"
     aria-labelledby="exampleModalLabel" aria-hidden="true" data-backdrop="static" data-keyboard="false">
</div>
<!-- End modal -->


<!-- Modal -->
<div class="modal fade" id="modal_delete_person" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">¿ Esta seguro ?</h5>
      </div>

        <input id="person_id" type="hidden">
        <input id="client_id" type="hidden">

      <div class="modal-footer">
        <button type="button" class="btn u-btn-red" onclick=delete_person()>Eliminar</button>
        <button type="button" class="btn u-btn-indigo" data-dismiss="modal">Cerrar</button>
      </div>
    </div>
  </div>
</div>

app/views/people/new.html.erb
<h1>New Person</h1>

<%= render 'form', client: @client %>

<%= link_to 'Back', client_persons_path %>

app/views/people/new.js.erb
$("#modal-person").html("<%= j (render 'form') %>")
$("#modal-person").modal('show')

var form_new_person = $('#form-new-person')

$('#person_person_type_id').select2({ width: '90%',theme: "bootstrap4" })

form_new_person.validate({
	rules: {
		'person[person_type_id]': {
			required: true,
			// Using the normalizer to trim the value of the element
			// before validating it.
			//
			// The value of `this` inside the `normalizer` is the corresponding
			// DOMElement. In this example, `this` references the `username` element.
			normalizer: function(value) {
				return $.trim(value);
			}
		},
		'person[name]': {
			required: true
		},
		'person[type_client]': {
			required: true
		},
		'person[dni]': {
			number: true
		},
		'person[phone]': {
			number: true
		}

	}
})

$("#form-new-person").on("ajax:success", function(event) {
  people_table.ajax.reload(null,false)
  noty_alert('success', 'Alta exitosa')
  $("#modal-person").modal('hide')
	}).on("ajax:error", function(event) {
	  $('#form-new-person #error_explanation').hide(500)
	  $('#form-new-person #error_list').empty()
		var msj = jQuery.parseJSON( event.detail[2].response )
		$.each( msj, function( key, value ) {
		  $('#form-new-person #error_list').append('<li> ' + key + ": " + value + ' </li>')
		})
		$('#form-new-person #error_explanation').show('slow')
})

app/views/people/reload_table.js.erb
$('#modal-person').modal('hide')

app/views/people/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Type person:</strong>
  <%= @person.type_person %>
</p>

<p>
  <strong>Name:</strong>
  <%= @person.name %>
</p>

<p>
  <strong>Surname:</strong>
  <%= @person.surname %>
</p>

<p>
  <strong>Dni:</strong>
  <%= @person.dni %>
</p>

<p>
  <strong>Email:</strong>
  <%= @person.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @person.phone %>
</p>

<p>
  <strong>Active:</strong>
  <%= @person.active %>
</p>

<p>
  <strong>Client:</strong>
  <%= @person.client %>
</p>

<%= link_to 'Edit', edit_client_person_path(@person) %> |
<%= link_to 'Back', client_persons_path %>

app/views/people/show.js.erb
$("#modal-person").html("<%= j (render 'show') %>")
$("#modal-person").modal('show')

app/views/people/update.js.erb
  people_table.ajax.reload(null,false)
  $('#modal-person').modal('hide')