config/routes.rb
Rails.application.routes.draw do
  root 'tickets#index'
  
  resources :clients do
  	resources :people
    resources :fleets
  end

  post 'disabled_client', to: 'clients#disabled', as: 'disabled_client'
  get 'clients/:client_id/people/:id/disable', to: 'people#disable'

  resources :users
  get 'users/:id/disable', to: 'users#disable'
  resources :sessions, only: [:new, :create, :destroy]
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :tickets do
    
    resources :ticket_answers
    # member do
    #   post '/tickets/close_ticket', to: 'tickets#close_ticket', as: 'close_ticket'
    # end
  end

  get 'tickets/get_tickets/:ticket_status_id', to: 'tickets#get_tickets', as: 'get_tickets'
  get 'count_tickets', to: 'tickets#count_tickets', as: 'count_tickets'
  get 'get_fleet/:client_id/:fleet_type_id', to: 'fleets#get_fleet', as: 'get_fleet'
  post 'assign_person', to: 'tickets#assign_person', as: 'assign_person'
  post 'close_ticket', to: 'tickets#close_ticket', as: 'close_ticket'

  # Reports
  resources :reports, only: [:index]
  get 'report_between_dates/:start_date/:end_date', to: 'reports#report_between_dates', as: 'report_between_dates', defaults: { format: 'xlsx' }

end

app/models/fleet.rb
class Fleet < ApplicationRecord
	belongs_to :client
	belongs_to :person, optional: true
end

app/models/fleet_type.rb
class FleetType < ApplicationRecord
end

app/controllers/fleets_controller.rb
class FleetsController < ApplicationController
  before_action :set_fleet, only: [:show, :edit, :update, :destroy]

  # GET /fleets
  # GET /fleets.json
  def index
    @client = Client.find(params[:client_id])
    @title = 'Equipos de ' + @client.name
    @fleets = Fleet.where(client_id: params[:client_id], active: true)
    @computers = { title: 'PC de escritorio', id: 'table_computers', 
                   cols: ['Código', 'IP', 'Hardware', 'Software', 'Encargado', 'Acciones'] }
    @notebooks = { title: 'Notebooks', id: 'table_notebookes',
                   cols: ['Código', 'Modelo', 'IP', 'Hardware', 'Software', 'Encargado', 'Acciones'] }
    @printers = { title: 'Impresoras', id: 'table_printers',
                   cols: ['Código', 'Modelo' ,'IP', 'Acciones'] }
    @network = { title: 'Equipos de red', id: 'table_network',
                   cols: ['Código', 'Modelo' ,'IP', 'Acciones'] }
    respond_to do |format|
      format.html
      format.js
      format.json
    end
  end

  # GET /fleets/1
  # GET /fleets/1.json
  def show
  end

  def get_fleet
    # Obtengo la flota por cliente y tipo , es para agregarlos a la tabla
    @fleets = Fleet.where(client_id: params[:client_id], fleet_type_id: params[:fleet_type_id], active: true)
    respond_to do |format|
      format.json
    end
  end

  # GET /fleets/new
  def new
    @client = Client.find(params[:client_id])
    @people = Person.where(client_id: params[:client_id])
    @operative_system = [ 'Windows 7', 'Windows 10', 'Windows XP', 'Archlinux', 'Debian', 'Ubuntu' ]
    respond_to do |format|
      format.js
    end
  end

  # GET /fleets/1/edit
  def edit
    respond_to do |format|
      format.js
    end
  end

  # POST /fleets
  # POST /fleets.json
  def create
    @client = Client.find(params[:client_id])
    @fleet = @client.fleets.create(fleet_params)

    respond_to do |format|
      if @fleet.save!
        format.html { redirect_to client_fleets_path(@client), notice: 'Fleet was successfully created.' }
        format.json { render 'success', status: :created, location: @fleet }
        format.js
      else
        format.html { render :new }
        format.json { render json: @fleet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fleets/1
  # PATCH/PUT /fleets/1.json
  def update
    respond_to do |format|
      if @fleet.update(fleet_params)
        format.html { redirect_to @fleet, notice: 'Fleet was successfully updated.' }
        format.json { render :show, status: :ok, location: @fleet }
      else
        format.html { render :edit }
        format.json { render json: @fleet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fleets/1
  # DELETE /fleets/1.json
  def destroy
    @fleet.destroy
    respond_to do |format|
      format.html { redirect_to fleets_url, notice: 'Fleet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fleet
      @fleet = Fleet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fleet_params
      params.require(:fleet).permit(:fleet_type_id, :code, :model, :os, :ip_address, :hardware, :software, :client_id, :person_id, :active)
    end
end

app/views/fleets/_form.html.erb
<div class="modal-dialog modal-lg" role="document">
  <div class="modal-content">
    <div class="modal-header">
      <h5 class="modal-title">Registro de equipo</h5>
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <div class="modal-body">
      <ul class="nav nav-tabs md-tabs" role="tablist">
        <li class="nav-item">
          <a class="nav-link active" data-toggle="tab" href="#dekstop" role="tab">PC Escritorio</a>
          <div class="slide"></div>
        </li>
        <li class="nav-item">
          <a class="nav-link" data-toggle="tab" href="#notebook" role="tab">Notebooks</a>
          <div class="slide"></div>
        </li>
        <li class="nav-item">
          <a class="nav-link" data-toggle="tab" href="#printers" role="tab">Impresoras</a>
          <div class="slide"></div>
        </li>
        <li class="nav-item">
          <a class="nav-link" data-toggle="tab" href="#network" role="tab">Red</a>
          <div class="slide"></div>
        </li>
      </ul>

      <div class="tab-content card-block">
        <div class="tab-pane active" id="dekstop" role="tabpanel">
          <%= render('form_computers', fleet_type: '1')%>
        </div>
        <div class="tab-pane" id="notebook" role="tabpanel">
          <%= render('form_notebooks', fleet_type: '2')%>
        </div>
        <div class="tab-pane" id="printers" role="tabpanel">
          <%= render('form_printers', fleet_type: '3')%>
        </div>
        <div class="tab-pane" id="network" role="tabpanel">
          <%= render('form_network', fleet_type: '4')%>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/fleets/_form_computers.html.erb
<%= form_with(model: [@client, @client.fleets.build], id: 'form-fleet') do |form| %>

  <input type="hidden" name="fleet[fleet_type_id]" id="fleet_fleet_type_id" value="<%= fleet_type %>" >

  <div class="form-group row">
    <%= form.label 'Código', class: 'col-3 col-form-label' %>
    <div class="col-9">
      <%= form.text_field :code, class: 'form-control rounded-0' %>
    </div>
  </div>

  <div class="form-group row">
    <label for="fleet_os" class="col-sm-3 col-form-label">Sistema Operativo</label>
    <div class="col-sm-6">
      <select id="fleet_os" name="fleet[os]" class="form-control select-2-fleet">
        <option disabled selected>Seleccione persona que usa</option>
        <% @operative_system.each do |os|  %>
          <option value="<%= os %>"><%= os %></option>
        <% end %>
      </select>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label 'IP', class: 'col-3 col-form-label' %>
    <div class="col-9">
      <%= form.text_field :ip_address, class: 'form-control rounded-0' %>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label 'Hardware', class: 'col-3 col-form-label' %>
    <div class="col-9">
      <%= form.text_field :hardware, class: 'form-control rounded-0' %>
    </div>
  </div>


  <div class="form-group row">
    <%= form.label 'Software', class: 'col-3 col-form-label' %>
    <div class="col-9">
      <%= form.text_field :software, class: 'form-control rounded-0', placeholder: 'Programas particulares del equipo' %>
    </div>
  </div>

  <div class="form-group row">
    <label for="fleet_person_id" class="col-sm-3 col-form-label">Usuario</label>
    <div class="col-sm-6">
      <select class="form-control select-2-fleet" id="fleet_person_id" name="fleet[person_id]">
        <option disabled selected>Seleccione persona que usa</option>
        <% @people.each do |p|  %>
          <option value="<%= p.id %>"><%= p.name %></option>
        <% end %>
      </select>
    </div>
  </div>

  <div class="actions">
    <%= form.submit 'Guardar', class: 'btn btn-primary' %>
    <button type="button" class="btn btn-danger" data-dismiss="modal">Cerrar</button>
  </div>
<% end %>

app/views/fleets/_form_network.html.erb
<%= form_with(model: [@client, @client.fleets.build], id: 'form-fleet-network') do |form| %>

  <input type="hidden" name="fleet[fleet_type_id]" id="fleet_fleet_type_id" value="<%= fleet_type %>" >

  <div class="form-group row">
    <%= form.label 'Código', class: 'col-3 col-form-label' %>
    <div class="col-9">
      <%= form.text_field :code, class: 'form-control rounded-0' %>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label 'Modelo', class: 'col-3 col-form-label' %>
    <div class="col-9">
      <%= form.text_field :model, class: 'form-control rounded-0' %>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label 'IP', class: 'col-3 col-form-label' %>
    <div class="col-9">
      <%= form.text_field :ip_address, class: 'form-control rounded-0' %>
    </div>
  </div>

  <div class="actions">
    <%= form.submit 'Guardar', class: 'btn btn-primary' %>
    <button type="button" class="btn btn-danger" data-dismiss="modal">Cerrar</button>
  </div>

<% end %>

app/views/fleets/_form_notebooks.html.erb
<%= form_with(model: [@client, @client.fleets.build], id: 'form-fleet-notebook') do |form| %>

  <input type="hidden" name="fleet[fleet_type_id]" id="fleet_fleet_type_id" value="<%= fleet_type %>" >

  <div class="form-group row">
    <%= form.label 'Código', class: 'col-3 col-form-label' %>
    <div class="col-9">
      <%= form.text_field :code, class: 'form-control rounded-0' %>
    </div>
  </div>

  <div class="form-group row">
    <label for="fleet_os" class="col-sm-3 col-form-label">Sistema Operativo</label>
    <div class="col-sm-6">
      <select id="fleet_os" name="fleet[os]" class="form-control select-2-fleet">
        <option disabled selected>Seleccione persona que usa</option>
        <% @operative_system.each do |os|  %>
          <option value="<%= os %>"><%= os %></option>
        <% end %>
      </select>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label 'Modelo', class: 'col-3 col-form-label' %>
    <div class="col-9">
      <%= form.text_field :model, class: 'form-control rounded-0' %>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label 'Hardware', class: 'col-3 col-form-label' %>
    <div class="col-9">
      <%= form.text_field :hardware, class: 'form-control rounded-0' %>
    </div>
  </div>


  <div class="form-group row">
    <%= form.label 'Software', class: 'col-3 col-form-label' %>
    <div class="col-9">
      <%= form.text_field :software, class: 'form-control rounded-0', placeholder: 'Programas particulares del equipo' %>
    </div>
  </div>

  <div class="form-group row">
    <label for="fleet_person_id" class="col-sm-3 col-form-label">Usuario</label>
    <div class="col-sm-6">
      <select class="form-control select-2-fleet" id="fleet_person_id" name="fleet[person_id]">
        <option disabled selected>Seleccione persona que usa</option>
        <% @people.each do |p|  %>
          <option value="<%= p.id %>"><%= p.name %></option>
        <% end %>
      </select>
    </div>
  </div>

  <div class="actions">
    <%= form.submit 'Guardar', class: 'btn btn-primary' %>
    <button type="button" class="btn btn-danger" data-dismiss="modal">Cerrar</button>
  </div>
<% end %>

app/views/fleets/_form_printers.html.erb
<%= form_with(model: [@client, @client.fleets.build], id: 'form-fleet-printer') do |form| %>

  <input type="hidden" name="fleet[fleet_type_id]" id="fleet_fleet_type_id" value="<%= fleet_type %>" >

  <div class="form-group row">
    <%= form.label 'Código', class: 'col-3 col-form-label' %>
    <div class="col-9">
      <%= form.text_field :code, class: 'form-control rounded-0' %>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label 'Modelo', class: 'col-3 col-form-label' %>
    <div class="col-9">
      <%= form.text_field :model, class: 'form-control rounded-0' %>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label 'IP', class: 'col-3 col-form-label' %>
    <div class="col-9">
      <%= form.text_field :ip_address, class: 'form-control rounded-0' %>
    </div>
  </div>

  <div class="form-group row">
    <label for="fleet_person_id" class="col-sm-3 col-form-label">Usuario</label>
    <div class="col-sm-6">
      <select class="form-control select-2-fleet" id="fleet_person_id" name="fleet[person_id]">
        <option disabled selected>Seleccione persona que usa</option>
        <% @people.each do |p|  %>
          <option value="<%= p.id %>"><%= p.name %></option>
        <% end %>
      </select>
    </div>
  </div>

  <div class="actions">
    <%= form.submit 'Guardar', class: 'btn btn-primary' %>
    <button type="button" class="btn btn-danger" data-dismiss="modal">Cerrar</button>
  </div>

<% end %>

app/views/fleets/_table_computers.html.erb
<div class="table-responsive dt-responsive">
  <table id="computers_table" class="table table-striped table-bordered nowrap w-100">
    <thead>
      <tr>
        <th>Código</th>
        <th>Usuario</th>
        <th>IP</th>
        <th>SO</th>
        <th>Hardware</th>
        <th>Software</th>
        <th>Acciones</th>
      </tr>
    </thead>
     <tbody> <!-- Ajax --> </tbody> 
  </table>
</div>

app/views/fleets/_table_network.html.erb
<div class="table-responsive dt-responsive">
  <table id="network_table" class="table table-striped table-bordered nowrap w-100">
    <thead>
      <tr>
        <th>Código</th>
        <th>Modelo</th>
        <th>IP</th>
        <th>Funcion</th>
        <th>Acciones</th>
      </tr>
    </thead>
     <tbody> <!-- Ajax --> </tbody> 
  </table>
</div>

app/views/fleets/_table_notebooks.html.erb
<div class="table-responsive dt-responsive">
  <table id="notebooks_table" class="table table-striped table-bordered nowrap w-100">
    <thead>
      <tr>
        <th>Código</th>
        <th>Usuario</th>
        <th>Modelo</th>
        <th>SO</th>
        <th>Hardware</th>
        <th>Software</th>
        <th>Acciones</th>
      </tr>
    </thead>
     <tbody> <!-- Ajax --> </tbody> 
  </table>
</div>

app/views/fleets/_table_printers.html.erb
<div class="table-responsive dt-responsive">
  <table id="printers_table" class="table table-striped table-bordered nowrap w-100">
    <thead>
      <tr>
        <th>Código</th>
        <th>Usuario</th>
        <th>Modelo</th>
        <th>IP</th>
        <th>Acciones</th>
      </tr>
    </thead>
     <tbody> <!-- Ajax --> </tbody> 
  </table>
</div>

app/views/fleets/create.js.erb
computers_table.ajax.reload(null,false)
$('#modal-fleet').modal('hide')

app/views/fleets/edit.html.erb
<h1>Editing Fleet</h1>

<%= render 'form', fleet: @fleet %>

<%= link_to 'Show', @fleet %> |
<%= link_to 'Back', fleets_path %>

app/views/fleets/index.html.erb
<div class="page-header card">
  <div class="row align-items-end">
    <div class="col-lg-8">
      <div class="page-header-title">
        <i class="ti-headphone-alt bg-c-blue"></i>
        <div class="d-inline">
          <h5>Flota</h5>
        <span>Información de Computadoras, impresoras y equipos de red.</span>
        </div>
      </div>
    </div>
    <div class="col-lg-4">
      <div class="page-header-breadcrumb">
        <ul class=" breadcrumb breadcrumb-title">
          <li class="breadcrumb-item">
            <%= link_to '<i class="ti-home"></i>'.html_safe, root_path %>
          </li>
          <li class="breadcrumb-item">
            <%= link_to 'Clientes', clients_path %>
          </li>
          <li class="breadcrumb-item">
            <%= link_to 'Flota', client_fleets_path %>
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>

<div class="pcoded-inner-content">
  <div class="main-body">
    <div class="page-wrapper">
      <div class="page-body">
        <div class="card">
          <div class="card-header">
            <%= link_to 'Registrar equipo <i class="fa fa-plus"></i>'.html_safe, new_client_fleet_path, 
                  {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modal-fleet', 'class' => 'btn btn-primary'} %>
          </div>
          <div class="card-block">
            <ul class="nav nav-tabs md-tabs" role="tablist">
              <li class="nav-item">
                <a class="nav-link active" data-toggle="tab" href="#desktop_list" role="tab">PC Escritorio</a>
                <div class="slide"></div>
              </li>
              <li class="nav-item">
                <a class="nav-link" data-toggle="tab" href="#notebooks_list" role="tab">Notebooks</a>
                <div class="slide"></div>
              </li>
              <li class="nav-item">
                <a class="nav-link" data-toggle="tab" href="#printers_list" role="tab">Impresoras</a>
                <div class="slide"></div>
              </li>
              <li class="nav-item">
                <a class="nav-link" data-toggle="tab" href="#network_list" role="tab">Red</a>
                <div class="slide"></div>
              </li>
            </ul>

            <div class="tab-content card-block">
              <div class="tab-pane active" id="desktop_list" role="tabpanel">
                <%= render('table_computers', table: @computers)%>
              </div>
              <div class="tab-pane" id="notebooks_list" role="tabpanel">
                <%= render('table_notebooks', table: @notebooks)%>
              </div>
              <div class="tab-pane" id="printers_list" role="tabpanel">
                <%= render('table_printers', table: @printers)%>
              </div>
              <div class="tab-pane" id="network_list" role="tabpanel">
                <%= render('table_network', table: @network)%>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- Modal para alta y edicion de persona -->
<div class="modal fade" id="modal-fleet" role="dialog"
     aria-labelledby="exampleModalLabel" aria-hidden="true" data-backdrop="static" data-keyboard="false">
</div>
<!-- End modal -->


<!-- Modal -->
<div class="modal fade" id="modal_delete_fleet" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">¿ Esta seguro ?</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>

        <input id="person_id" type="hidden">
        <input id="client_id" type="hidden">

      <div class="modal-footer">
        <button type="button" class="btn u-btn-red" onclick=delete_person()>Eliminar</button>
        <button type="button" class="btn u-btn-indigo" data-dismiss="modal">Cerrar</button>
      </div>
    </div>
  </div>
</div>

  <!-- Lo uso para conservar el id del cliente -->
<input type="hidden" id="fleets_client_id" name="fleets_client_id" value='<%= @client.id %>' >

app/views/fleets/new.js.erb
$("#modal-fleet").html("<%= j (render 'form') %>")
$("#modal-fleet").modal('show')

// $('#fleet_person_id').select2({ width: '90%',theme: "bootstrap4" })
// $('#fleet_os').select2({ width: '90%',theme: "bootstrap4" }) 
$('.select-2-fleet').select2({ width: '90%',theme: "bootstrap4" }) 

$("#form-fleet").on("ajax:success", function(event) {
  computers_table.ajax.reload(null,false)
	$('#modal-fleet').modal('hide')
	
  noty_alert('success', 'Alta exitosa')

}).on("ajax:error", function(event) {
  noty_alert('error', 'No se pudo cargar la información')
})

$("#form-fleet-notebook").on("ajax:success", function(event) {
  notebooks_table.ajax.reload(null,false)
  $('#modal-fleet').modal('hide')

  noty_alert('success', 'Alta exitosa')  

}).on("ajax:error", function(event) {
  noty_alert('error', 'No se pudo cargar la información')
})

$("#form-fleet-network").on("ajax:success", function(event) {
  network_table.ajax.reload(null,false)
  $('#modal-fleet').modal('hide')

  noty_alert('success', 'Alta exitosa')  

}).on("ajax:error", function(event) {
  noty_alert('error', 'No se pudo cargar la información')
})

$("#form-fleet-printer").on("ajax:success", function(event) {
  printers_table.ajax.reload(null,false)
  $('#modal-fleet').modal('hide')

  noty_alert('success', 'Alta exitosa')  

}).on("ajax:error", function(event) {
  noty_alert('error', 'No se pudo cargar la información')
})

app/views/fleets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Type fleet:</strong>
  <%= @fleet.type_fleet %>
</p>

<p>
  <strong>Code:</strong>
  <%= @fleet.code %>
</p>

<p>
  <strong>Ip address:</strong>
  <%= @fleet.ip_address %>
</p>

<p>
  <strong>Hardware:</strong>
  <%= @fleet.hardware %>
</p>

<p>
  <strong>Software:</strong>
  <%= @fleet.software %>
</p>

<p>
  <strong>Client:</strong>
  <%= @fleet.client %>
</p>

<%= link_to 'Edit', edit_fleet_path(@fleet) %> |
<%= link_to 'Back', fleets_path %>