config/routes.rb
Rails.application.routes.draw do
  root 'tickets#index'
  
  resources :clients do
  	resources :people
    resources :fleets
  end

  post 'disabled_client', to: 'clients#disabled', as: 'disabled_client'
  get 'clients/:client_id/people/:id/disable', to: 'people#disable'

  resources :users
  get 'users/:id/disable', to: 'users#disable'
  resources :sessions, only: [:new, :create, :destroy]
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :tickets do
    
    resources :ticket_answers
    # member do
    #   post '/tickets/close_ticket', to: 'tickets#close_ticket', as: 'close_ticket'
    # end
  end

  get 'tickets/get_tickets/:ticket_status_id', to: 'tickets#get_tickets', as: 'get_tickets'
  get 'count_tickets', to: 'tickets#count_tickets', as: 'count_tickets'
  get 'get_fleet/:client_id/:fleet_type_id', to: 'fleets#get_fleet', as: 'get_fleet'
  post 'assign_person', to: 'tickets#assign_person', as: 'assign_person'
  post 'close_ticket', to: 'tickets#close_ticket', as: 'close_ticket'

  # Reports
  resources :reports, only: [:index]
  get 'report_between_dates/:start_date/:end_date', to: 'reports#report_between_dates', as: 'report_between_dates', defaults: { format: 'xlsx' }

end

app/models/user.rb
class User < ApplicationRecord
	belongs_to :person
	belongs_to :rol
  has_many :tickets
  has_many :ticket_answers
  
  has_secure_password
  validates :email, presence: true, uniqueness: true
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :disable]

  # GET /users
  # GET /users.json
  def index
    @users = User.where(active: true).order(username: :asc)
    @title = 'Usuarios'
    respond_to do |format|
      format.html
      format.json
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
    @clients = Client.all
    respond_to do |format|
      format.js
    end
  end

  # GET /users/1/edit
  def edit
    @clients = Client.all
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save!
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
        format.js
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        # format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render json: {status: 'success'}, status: :created, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    respond_to do |format|
      if @user.update(active: false)
        render json: { status: 'success' }
      else
        format.html { redirect_to users_url, notice: 'No se pudo dar de baja el usuario.' }
      end
    end
  end

  def disable
    if @user.update(active: false)
      render json: { status: 'success' }
    else
      render json: { status: 'error' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :email, :password, :password_confirmation, :person_id, :rol_id, :avatar)
    end
end

app/views/users/_form.html.erb
<%= form_with(model: @user, id: 'form-user') do |form| %>
  <div id="error_explanation" class="alert alert-danger" style="display:none">
    <ul id="error_list"></ul>
  </div>

  <div class="form-group row">
    <label for="rol_id" class="col-sm-3 col-form-label">Tipo</label>
    <div class="col-sm-6">
      <select class="form-control select-person" id="user_rol_id" name="user[rol_id]" class="form-control">
        <option disabled selected>Seleccione tipo</option>
        <% if !@user.nil? && @user.rol_id == 1 %>
          <option value="1" selected>Administrador</option>
        <% else %>
          <option value="1">Administrador</option>
        <% end %>
        <% if !@user.nil? && @user.rol_id == 2 %>
          <option value="2" selected>Cliente</option>
        <% else %>
          <option value="2">Cliente</option>
        <% end %>
        
      </select>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label :username,'Nombre de usuario', class: 'col-sm-3 col-form-label' %>
    <div class="col-9">
      <%= form.text_field :username, class: 'form-control rounded-0' %>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label :email,'Email', class: 'col-sm-3 col-form-label' %>
    <div class="col-9">
      <%= form.text_field :email, class: 'form-control rounded-0' %>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label :password,'Contraseña', class: 'col-sm-3 col-form-label' %>
    <div class="col-9">
      <%= form.password_field :password, class: 'form-control rounded-0' %>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label :password_confirmation,'Confirmar contraseña', class: 'col-sm-3 col-form-label' %>
    <div class="col-9">
      <%= form.password_field :password_confirmation, class: 'form-control rounded-0' %>
    </div>
  </div>

  <div class="form-group row">
    <label for="client_id" class="col-sm-3 col-form-label">Cliente</label>
    <div class="col-sm-6">
      <select class="form-control select-person" id="user_client_id" name="user[client_id]" class="form-control">
        <option disabled selected>Seleccione cliente</option>
        <% @clients.each do |t|  %>
          <% if !@user.person_id.nil? && t.id == @user.person.client_id %>
            <option value="<%= t.id %>" selected><%= t.name %></option>
          <% else %>
            <option value="<%= t.id %>"><%= t.name %></option>  
          <% end %>
        <% end %>
      </select>
    </div>
  </div>

  <% if !@user.person_id.nil? %>
    <input type="hidden" id="user_person_id_edit" value="<%= @user.person_id %>">
  <% end %>

  <div class="form-group row">
    <label for="user_person_id" class="col-sm-3 col-form-label">Persona</label>
    <div class="col-sm-6">
      <select class="form-control select-person" id="user_person_id" name="user[person_id]" class="form-control">
        <option disabled selected>Seleccione persona</option>
        <!-- ajax -->
      </select>
    </div>
  </div>

  <div class="form-group row text-center">
    <label for="user_avatar" class="col-sm-3 col-form-label">Avatar</label>
    <div class="col-md-12 col-lg-12 col-sm-12 mb-2">
      <div class="form-radio">
        <div class="radio radio-inline col-md-3 col-lg-3 col-sm-2 col-3">
            <div class="row">
              <img class="img-fluid img-radius" alt="Responsive image" src="/assets/avatars/avatar2.png">
            </div>
            <label>
                <input type="radio" id="user_avatar" name="user[avatar]" value="avatar2.png">
                <i class="helper"></i>
            </label>
        </div>
        <div class="radio radio-inline col-md-3 col-lg-3 col-sm-2 col-3">
          <div class="row">
            <img class="img-fluid img-radius" alt="Responsive image" src="/assets/avatars/avatar_female.png">
          </div>
          <label>
              <input type="radio" id="user_avatar" name="user[avatar]" value="avatar_female.png" required>
              <i class="helper"></i>
          </label>
        </div>
      </div>
    </div>
  </div>

  <div class="actions">
    <%= form.submit 'Agregar', class: 'btn btn-primary' %>
    <button type="button" class="btn btn-danger modal-user">Cerrar</button>
  </div>
<% end %>

app/views/users/_modal_new_user.html.erb
<div class="modal-dialog" role="document">
  <div class="modal-content">
    <div class="modal-header">
      <h5 class="modal-title">Nuevo usuario</h5>
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <div class="modal-body">
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/edit.js.erb
$("#modal-user").html("<%= j (render 'modal_new_user') %>")
$("#modal-user").modal('show')



$('.select-person').select2({ width: '100%',theme: "bootstrap4" })

// function populate_people_select()
// {
// 	$.ajax({
// 	  url: '/clients/' + $("#form-user #client_id").val() + '/people',
// 	  type: 'GET',
// 	  dataType: 'JSON',
// 	  success: function ( resp ) {
// 	    $('#form-user #user_person_id').find('option').remove().end().append('<option value="" disabled selected>Solicito el servicio</option>');
// 	    $( resp.data ).each(function(i, element){
// 	    	if (true) {}
// 	      $("#form-user #ticket_person_id").append("<option value="+element.id +">"+element.name + " " + element.surname + "</option>")
// 	    })
// 	  }
// 	})	
// }
function print_client_people()
{
  let user_person_id = $('#user_person_id_edit').val()
  $.ajax({
    url: '/clients/' + $("#form-user #user_client_id").val() + '/people',
    type: 'GET',
    dataType: 'JSON',
    success: function ( resp ) {
      // $('#form-user #user_person_id').find('option').remove().end().append('<option value="" disabled selected>Persona</option>');
      $( resp.data ).each(function(i, element){
        if ( user_person_id == element.id ) {
          $("#form-user #user_person_id").append("<option value="+element.id +" selected >"+element.name + " " + element.surname + "</option>")
        } else {
          $("#form-user #user_person_id").append("<option value="+element.id +">"+element.name + " " + element.surname + "</option>")
        }
      })
    }
  })
}

print_client_people()

$("#form-user").on("ajax:success", function(event) {
  users_table.ajax.reload(null,false)
  noty_alert('success', 'Edición exitosa')
  $("#modal-user").modal('hide')
}).on("ajax:error", function(event) {
  $('#form-user #error_explanation').hide(500)
  $('#form-user #error_list').empty()
  var msj = jQuery.parseJSON( event.detail[2].response )
  $.each( msj, function( key, value ) {
    $('#form-user #error_list').append('<li> ' + key + ": " + value + ' </li>')
  })
  $('#form-user #error_explanation').show('slow')
})

app/views/users/index.html.erb
<div class="page-header card">
  <div class="row align-items-end">
    <div class="col-lg-8">
      <div class="page-header-title">
        <i class="ti-user bg-c-blue"></i>
        <div class="d-inline">
          <h5>Usuarios</h5>
        <span>Descripcion de la vista</span>
        </div>
      </div>
    </div>
    <div class="col-lg-4">
      <div class="page-header-breadcrumb">
        <ul class=" breadcrumb breadcrumb-title">
          <li class="breadcrumb-item">
            <%= link_to '<i class="ti-home"></i>'.html_safe, root_path %>
          </li>
          <li class="breadcrumb-item">
            <%= link_to 'Usuarios', users_path %>
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>

<div class="pcoded-inner-content">
  <div class="main-body">
    <div class="page-wrapper">
      <div class="page-body">
        <div class="card">
          <div class="card-header">
            <%= link_to 'Nuevo usuario', signup_path, {:remote => true, 'data-toggle' =>  "modal",
                                                 'data-target' => '#modal-user', 'class' => 'btn btn-primary'} %>
          </div>
          <div class="card-block">
            <div class="table-responsive dt-responsive">
              <table id="users_table" class="table table-striped table-bordered nowrap w-100">
                <thead>
                  <tr>
                    <th>Nombre de usuario</th>
                    <th>Email</th>
                    <th>Cliente</th>
                    <th>Persona</th>
                    <th>Acciones</th>
                  </tr>
                </thead>
                 <tbody> <!-- Ajax --> </tbody> 
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

<!-- Modal para alta y edicion de usuario -->
<div class="modal" id="modal-user" role="dialog"
     aria-labelledby="modalUserLabel" aria-hidden="true" data-backdrop="static" data-keyboard="false">
</div>
<!-- End modal -->


<!-- Modal -->
<div class="modal fade" id="modal_delete_user" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">¿ Esta seguro ?</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>

        <input id="user_id" type="hidden">

      <div class="modal-footer">
        <button type="button" class="btn btn-primary" onclick=delete_user()>Eliminar</button>
        <button type="button" class="btn btn-danger" data-dismiss="modal">Cerrar</button>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/new.js.erb
$("#modal-user").html("<%= j (render 'modal_new_user') %>")
$("#modal-user").modal('show')

$('.select-person').select2({ width: '100%',theme: "bootstrap4" })

  $("#form-user #user_client_id").on('change', function(event) {
    $.ajax({
      url: '/clients/' + $(this).val() + '/people',
      type: 'GET',
      dataType: 'JSON',
      success: function ( resp ) {
        $('#form-user #user_person_id').find('option').remove().end().append('<option value="" disabled selected>Solicito el servicio</option>');
        $( resp.data ).each(function(i, element){
          console.log( element.name )
          $("#form-user #user_person_id").append("<option value="+element.id +">"+element.name + " " + element.surname + "</option>")
        })
      }
    })
  }) // End on change


  $('.modal-user').on('click',function(){
    console.log('click')
    $('#modal-user').modal('hide')
  })

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Person:</strong>
  <%= @user.person %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>