config/routes.rb
Rails.application.routes.draw do
  root 'tickets#index'
  
  resources :clients do
  	resources :people
    resources :fleets
  end

  post 'disabled_client', to: 'clients#disabled', as: 'disabled_client'
  get 'clients/:client_id/people/:id/disable', to: 'people#disable'

  resources :users
  get 'users/:id/disable', to: 'users#disable'
  resources :sessions, only: [:new, :create, :destroy]
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :tickets do
    
    resources :ticket_answers
    # member do
    #   post '/tickets/close_ticket', to: 'tickets#close_ticket', as: 'close_ticket'
    # end
  end

  get 'tickets/get_tickets/:ticket_status_id', to: 'tickets#get_tickets', as: 'get_tickets'
  get 'count_tickets', to: 'tickets#count_tickets', as: 'count_tickets'
  get 'get_fleet/:client_id/:fleet_type_id', to: 'fleets#get_fleet', as: 'get_fleet'
  post 'assign_person', to: 'tickets#assign_person', as: 'assign_person'
  post 'close_ticket', to: 'tickets#close_ticket', as: 'close_ticket'

  # Reports
  resources :reports, only: [:index]
  get 'report_between_dates/:start_date/:end_date', to: 'reports#report_between_dates', as: 'report_between_dates', defaults: { format: 'xlsx' }

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
	belongs_to :client_type
	belongs_to :iva_condition, required: false
	belongs_to :sale_condition, required: false

	has_many :people
	has_many :fleets
  has_many :computers
  has_many :tickets

	validates :name, presence: true, length: { minimum: 3 }, uniqueness: true
end

app/models/client_type.rb
class ClientType < ApplicationRecord
	has_many :clients
end

app/models/fleet.rb
class Fleet < ApplicationRecord
	belongs_to :client
	belongs_to :person, optional: true
end

app/models/fleet_type.rb
class FleetType < ApplicationRecord
end

app/models/iva_condition.rb
class IvaCondition < ApplicationRecord
	has_many :clients
end

app/models/person.rb
class Person < ApplicationRecord
  belongs_to :client
  belongs_to :person_type
  has_many :tickets
  has_many :fleets
  # has_many :assigned_tickets, :class_name => 'Ticket', :foreign_key => 'assigned_to' 
  # has_one :user
	validates :name, presence: true,
						length: { minimum: 3 }
	validates :person_type, presence: true
end

app/models/person_type.rb
class PersonType < ApplicationRecord
	has_many :people
end

app/models/rol.rb
class Rol < ApplicationRecord
	has_many :users
end

app/models/sale_condition.rb
class SaleCondition < ApplicationRecord
	has_many :clients
end

app/models/ticket.rb
class Ticket < ApplicationRecord
	belongs_to :ticket_type
	belongs_to :ticket_status
	belongs_to :client
  belongs_to :person, required: false
  belongs_to :fleet, optional: true
  belongs_to :user
  belongs_to :assigned, :class_name => 'Person', :foreign_key => 'assigned_to', optional: true
  has_many :ticket_answers
  has_many_attached :images
end

app/models/ticket_answer.rb
class TicketAnswer < ApplicationRecord
	belongs_to :ticket
	belongs_to :user
	has_many_attached :images
end

app/models/ticket_priority.rb
class TicketPriority < ApplicationRecord
end

app/models/ticket_status.rb
class TicketStatus < ApplicationRecord
	has_many :tickets
end

app/models/ticket_type.rb
class TicketType < ApplicationRecord
	has_many :tickets
end

app/models/user.rb
class User < ApplicationRecord
	belongs_to :person
	belongs_to :rol
  has_many :tickets
  has_many :ticket_answers
  
  has_secure_password
  validates :email, presence: true, uniqueness: true
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :disable]

  # GET /users
  # GET /users.json
  def index
    @users = User.where(active: true).order(username: :asc)
    @title = 'Usuarios'
    respond_to do |format|
      format.html
      format.json
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
    @clients = Client.all
    respond_to do |format|
      format.js
    end
  end

  # GET /users/1/edit
  def edit
    @clients = Client.all
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save!
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
        format.js
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        # format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render json: {status: 'success'}, status: :created, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    respond_to do |format|
      if @user.update(active: false)
        render json: { status: 'success' }
      else
        format.html { redirect_to users_url, notice: 'No se pudo dar de baja el usuario.' }
      end
    end
  end

  def disable
    if @user.update(active: false)
      render json: { status: 'success' }
    else
      render json: { status: 'error' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :email, :password, :password_confirmation, :person_id, :rol_id, :avatar)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/layouts/_example_header_with_navs.html.erb
<div class="loader-bg">
	<div class="loader-bar"></div>
</div>

<div id="pcoded" class="pcoded">
	<div class="pcoded-overlay-box"></div>
	<div class="pcoded-container navbar-wrapper">

		<nav class="navbar header-navbar pcoded-header">
			<div class="navbar-wrapper">
				<div class="navbar-logo">
					<%= link_to root_path do %>
						<img class="img-fluid" src="/assets/logoMS.png" alt="logo" />
					<% end %>
					<a class="mobile-menu" id="mobile-collapse" href="#!">
						<i class="ti-menu"></i>
					</a>
					<a class="mobile-options waves-effect waves-light">
						<i class="ti-more"></i>
					</a>
				</div>
				<div class="navbar-container container-fluid">
					<ul class="nav-right">
						<li class="header-notification">
							<div class="dropdown-primary dropdown">
								<div class="dropdown-toggle" data-toggle="dropdown">
									<i class="ti-bell"></i>
									<span class="badge bg-c-red">5</span>
								</div>
								<ul class="show-notification notification-view dropdown-menu" data-dropdown-in="fadeIn" data-dropdown-out="fadeOut">
									<li>
										<h6>Notifications</h6>
										<label class="label label-danger">New</label>
									</li>
									<li>
										<div class="media">
											<img class="img-radius" src="/assets/avatar2.png" alt="Generic placeholder image">
											<div class="media-body">
												<h5 class="notification-user">John Doe</h5>
												<p class="notification-msg">Lorem ipsum dolor sit amet, consectetuer elit.</p>
												<span class="notification-time">30 minutes ago</span>
											</div>
										</div>
									</li>
								<li>
								<div class="media">
									<img class="img-radius" src="/assets/avatar2.png" alt="Generic placeholder image">
									<div class="media-body">
										<h5 class="notification-user">Joseph William</h5>
										<p class="notification-msg">Lorem ipsum dolor sit amet, consectetuer elit.</p>
										<span class="notification-time">30 minutes ago</span>
									</div>
								</div>
								</li>
								<li>
									<div class="media">
										<img class="img-radius" src="/assets/avatar2.png" alt="Generic placeholder image">
										<div class="media-body">
											<h5 class="notification-user">Sara Soudein</h5>
											<p class="notification-msg">Lorem ipsum dolor sit amet, consectetuer elit.</p>
											<span class="notification-time">30 minutes ago</span>
										</div>
									</div>
								</li>
								</ul>
							</div>
						</li>
						<li class="header-notification">
							<div class="dropdown-primary dropdown">
								<div class="displayChatbox dropdown-toggle" data-toggle="dropdown">
									<i class="ti-email"></i>
									<span class="badge bg-c-green">3</span>
								</div>
							</div>
						</li>
						<li class="user-profile header-notification">
							<div class="dropdown-primary dropdown">
								<div class="dropdown-toggle" data-toggle="dropdown">
									<img src="/assets/avatar2.png" class="img-radius" alt="User-Profile-Image">
									<span>John Doe</span>
									<i class="ti-angle-down"></i>
								</div>
								<ul class="show-notification profile-notification dropdown-menu" data-dropdown-in="fadeIn" data-dropdown-out="fadeOut">
									<li>
										<a href="auth-sign-in-social.html">
											<i class="ti-shift-right"></i> Salir
										</a>
									</li>
								</ul>
							</div>
						</li>
					</ul>
				</div>
			</div>
		</nav>

		<div id="sidebar" class="users p-chat-user showChat">
			<div class="had-container">
				<div class="p-fixed users-main">
					<div class="user-box">
						<div class="chat-search-box">
							<a class="back_friendlist">
								<i class="feather icon-x"></i>
							</a>
							<div class="right-icon-control">
								<div class="input-group input-group-button">
									<input type="text" id="search-friends" name="footer-email" class="form-control" placeholder="Search Friend">
									<div class="input-group-append">
										<button class="btn btn-primary waves-effect waves-light" type="button"><i class="feather icon-search"></i></button>
									</div>
								</div>
							</div>
						</div>
						<div class="main-friend-list">
							<div class="media userlist-box waves-effect waves-light" data-id="1" data-status="online" data-username="Josephin Doe">
								<a class="media-left" href="#!">
									<img class="media-object img-radius img-radius" src="/assets/avatar2.png" alt="Generic placeholder image ">
									<div class="live-status bg-success"></div>
								</a>
								<div class="media-body">
									<div class="chat-header">Josephin Doe</div>
								</div>
							</div>
							<div class="media userlist-box waves-effect waves-light" data-id="2" data-status="online" data-username="Lary Doe">
								<a class="media-left" href="#!">
									<img class="media-object img-radius" src="/assets/avatar2.png" alt="Generic placeholder image">
									<div class="live-status bg-success"></div>
								</a>
								<div class="media-body">
									<div class="f-13 chat-header">Lary Doe</div>
								</div>
							</div>
							<div class="media userlist-box waves-effect waves-light" data-id="3" data-status="online" data-username="Alice">
								<a class="media-left" href="#!">
									<img class="media-object img-radius" src="/assets/avatar2.png" alt="Generic placeholder image">
									<div class="live-status bg-success"></div>
								</a>
								<div class="media-body">
									<div class="f-13 chat-header">Alice</div>
								</div>
							</div>
							<div class="media userlist-box waves-effect waves-light" data-id="4" data-status="offline" data-username="Alia">
								<a class="media-left" href="#!">
									<img class="media-object img-radius" src="/assets/avatar2.png" alt="Generic placeholder image">
									<div class="live-status bg-default"></div>
								</a>
								<div class="media-body">
									<div class="f-13 chat-header">Alia<small class="d-block text-muted">10 min ago</small></div>
								</div>
							</div>
							<div class="media userlist-box waves-effect waves-light" data-id="5" data-status="offline" data-username="Suzen">
								<a class="media-left" href="#!">
									<img class="media-object img-radius" src="/assets/avatar2.png" alt="Generic placeholder image">
									<div class="live-status bg-default"></div>
								</a>
								<div class="media-body">
									<div class="f-13 chat-header">Suzen<small class="d-block text-muted">15 min ago</small></div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>

		<div class="showChat_inner">
			<div class="media chat-inner-header">
				<a class="back_chatBox">
					<i class="feather icon-x"></i> Josephin Doe
				</a>
			</div>
			<div class="main-friend-chat">
				<div class="media chat-messages">
					<a class="media-left photo-table" href="#!">
						<img class="media-object img-radius img-radius m-t-5" src="/assets/avatar2.png" alt="Generic placeholder image">
					</a>
					<div class="media-body chat-menu-content">
						<div class="">
							<p class="chat-cont">I'm just looking around. Will you tell me something about yourself?</p>
						</div>
						<p class="chat-time">8:20 a.m.</p>
					</div>
				</div>
				<div class="media chat-messages">
					<div class="media-body chat-menu-reply">
						<div class="">
							<p class="chat-cont">Ohh! very nice</p>
						</div>
						<p class="chat-time">8:22 a.m.</p>
					</div>
				</div>
				<div class="media chat-messages">
					<a class="media-left photo-table" href="#!">
						<img class="media-object img-radius img-radius m-t-5" src="/assets/avatar2.png" alt="Generic placeholder image">
					</a>
					<div class="media-body chat-menu-content">
						<div class="">
							<p class="chat-cont">can you come with me?</p>
						</div>
						<p class="chat-time">8:20 a.m.</p>
					</div>
				</div>
			</div>
			<div class="chat-reply-box">
				<div class="right-icon-control">
					<div class="input-group input-group-button">
						<input type="text" class="form-control" placeholder="Write hear . . ">
						<div class="input-group-append">
							<button class="btn btn-primary waves-effect waves-light" type="button"><i class="feather icon-message-circle"></i></button>
						</div>
					</div>
				</div>
			</div>
		</div>

		<div class="pcoded-main-container">
			<div class="pcoded-wrapper">
				<nav class="pcoded-navbar">
					<div class="pcoded-inner-navbar">
						<ul class="pcoded-item">
							<li class="">
								<%= link_to '<i class="ti-headphone-alt"></i> Tickets'.html_safe, tickets_path, class: 'pcoded-mtext' %>
							</li>
							<li>
								<%= link_to '<i class="ti-user"></i> Clientes'.html_safe, clients_path, class: 'pcoded-mtext' %>
							</li>
							<li>
								<%= link_to '<i class="ti-lock"></i>Usuarios'.html_safe, users_path, class: 'pcoded-mtext' %>
							</li>
						</ul>  <!-- end menu -->
					</div>
				</nav>

app/views/layouts/_footer.html.erb
    <!-- Copyright Footer -->
    <footer class="g-bg-gray-dark-v1 g-color-white-opacity-0_8 g-py-20 footer">
      <div class="container">
        <div class="row">
          <div class="col-md-8 text-center text-md-left g-mb-10 g-mb-0--md">
            <div class="d-lg-flex">
              <ul class="u-list-inline">
                <li class="list-inline-item">
                  <small class="d-block g-font-size-default g-mr-10 g-mb-10 g-mb-0--md">
                    2018 &copy; Todos los derechos reservados.
                  </small>
                </li>
                <li class="list-inline-item">
                  <span>|</span>
                </li>
                <li class="list-inline-item">
                  <small class="d-block g-font-size-default g-mr-10 g-mb-10 g-mb-0--md">
                    Desarrollado por David Almirón para Mauro Sampaoli
                  </small>
                </li>
              </ul>
            </div>
          </div>

          <div class="col-md-4 align-self-center">
            <ul class="list-inline text-center text-md-right mb-0">
              <li class="list-inline-item g-mx-10" data-toggle="tooltip" data-placement="top" title="Facebook">
                <a href="#!" class="g-color-white-opacity-0_5 g-color-white--hover">
                  <i class="fa fa-facebook"></i>
                </a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </footer>
    <!-- End Copyright Footer -->

app/views/layouts/_header.html.erb
<div class="loader-bg">
	<div class="loader-bar"></div>
</div>

<div id="pcoded" class="pcoded">
	<div class="pcoded-overlay-box"></div>
	<div class="pcoded-container navbar-wrapper">

		<nav class="navbar header-navbar pcoded-header">
			<div class="navbar-wrapper">
				<div class="navbar-logo">
					<%= link_to root_path do %>
						<img class="img-fluid" src="/assets/logoMS.png" alt="logo" />
					<% end %>
					<a class="mobile-menu" id="mobile-collapse" href="#!">
						<i class="ti-menu"></i>
					</a>
					<a class="mobile-options waves-effect waves-light">
						<i class="ti-more"></i>
					</a>
				</div>
				<div class="navbar-container container-fluid">
					<ul class="nav-right">

						<li class="user-profile header-notification">
							<div class="dropdown-primary dropdown">
								<div class="dropdown-toggle" data-toggle="dropdown">
									<img src="/assets/avatars/<%= current_user.avatar %>" class="img-radius" alt="User-Profile-Image">
									<span><%= current_user.person.name %></span>
									<i class="ti-angle-down"></i>
								</div>
								<ul class="show-notification profile-notification dropdown-menu" data-dropdown-in="fadeIn" data-dropdown-out="fadeOut">
									<li>
										<%= link_to '<i class="ti-shift-right"></i> Salir'.html_safe, logout_path %>
									</li>
								</ul>
							</div>
						</li>
					</ul>
				</div>
			</div>
		</nav>

		<div class="pcoded-main-container">
			<div class="pcoded-wrapper">
				<nav class="pcoded-navbar">
					<div class="pcoded-inner-navbar">
						<ul class="pcoded-item">
							<li class="">
								<%= link_to '<i class="ti-headphone-alt"></i> Tickets'.html_safe, tickets_path, class: 'pcoded-mtext' %>
							</li>
							<% if current_user.rol.name == 'Administrador' %>
							<li>
								<%= link_to '<i class="ti-user"></i> Clientes'.html_safe, clients_path, class: 'pcoded-mtext' %>
							</li>
							<li>
								<%= link_to '<i class="ti-lock"></i>Usuarios'.html_safe, users_path, class: 'pcoded-mtext' %>
							</li>
							<li>
								<%= link_to '<i class="ti-layout-cta-btn-right"></i>Reportes'.html_safe, reports_path, class: 'pcoded-mtext' %>
							</li>
							<% end %>
						</ul>  <!-- end menu -->
					</div>
				</nav>

app/views/layouts/_nav.html.erb
<!-- <div id="sidebar" class="users p-chat-user showChat">
  <div class="had-container">
      <div class="p-fixed users-main">
        <div class="user-box">
          <div class="chat-search-box">
            <a class="back_friendlist">
              <i class="feather icon-x"></i>
            </a>
            <div class="right-icon-control">
              <div class="input-group input-group-button">
                <input type="text" id="search-friends" name="footer-email" class="form-control" placeholder="Search Friend">
                <div class="input-group-append">
                  <button class="btn btn-primary waves-effect waves-light" type="button"><i class="feather icon-search"></i></button>
                </div>
              </div>
            </div>
          </div>
          <div class="main-friend-list">
            <div class="media userlist-box waves-effect waves-light" data-id="1" data-status="online" data-username="Josephin Doe">
              <a class="media-left" href="#!">
                <img class="media-object img-radius img-radius" src="/assets/isologo.png" alt="Generic placeholder image ">
                <div class="live-status bg-success"></div>
              </a>
              <div class="media-body">
                <div class="chat-header">Josephin Doe</div>
              </div>
            </div>
            <div class="media userlist-box waves-effect waves-light" data-id="2" data-status="online" data-username="Lary Doe">
              <a class="media-left" href="#!">
                <img class="media-object img-radius" src="../files/assets/images/avatar-2.jpg" alt="Generic placeholder image">
                <div class="live-status bg-success"></div>
              </a>
              <div class="media-body">
                <div class="f-13 chat-header">Lary Doe</div>
              </div>
            </div>
          </div>
        </div>
    </div>
  </div>
</div> -->
<div class="pcoded-main-container">
<div class="pcoded-wrapper">

<nav class="pcoded-navbar">
  <div class="nav-list">
    <div class="pcoded-inner-navbar main-menu">
      <ul class="pcoded-item pcoded-left-item">
        <li>
          <%= link_to '<span class="pcoded-micon"><i class="ti-headphone-alt"></i></span>
                      <span class="pcoded-mtext">Tickets</span>'.html_safe, 
                      tickets_path, class: "waves-effect waves-dark" %>
        </li>
        <% if current_user.rol.name == "Administrador" %>
        <li>
          <%= link_to '<span class="pcoded-micon"><i class="ti-user"></i></span>
                      <span class="pcoded-mtext">Clientes</span>'.html_safe, 
                      clients_path, class: "waves-effect waves-dark" %>
        </li>
        <li>
          <%= link_to '<span class="pcoded-micon"><i class="ti-user"></i></span>
                      <span class="pcoded-mtext">Usuarios</span>'.html_safe, 
                      users_path, class: "waves-effect waves-dark" %>
        </li>
        <% end %>
<!--         <li class="pcoded-hasmenu">
          <a href="javascript:void(0)" class="waves-effect waves-dark">
            <span class="pcoded-micon"><i class="ti-headphone-alt"></i></span>
            <span class="pcoded-mtext">Tickets</span>
          </a>
          <ul class="pcoded-submenu">
            <li class="">
              <a href="index.html" class="waves-effect waves-dark">
                <span class="pcoded-mtext">Default</span>
              </a>
            </li>
            <li class="">
              <a href="dashboard-analytics.html" class="waves-effect waves-dark">
                <span class="pcoded-mtext">Analytics</span>
                <span class="pcoded-badge label label-info ">NEW</span>
              </a>
            </li>
          </ul>
        </li>
        <li class="pcoded-hasmenu">
          <a href="javascript:void(0)" class="waves-effect waves-dark">
           <span class="pcoded-micon"><i class="ti-user"></i></span>
            <span class="pcoded-mtext">Clientes</span>
            <span class="pcoded-badge label label-warning">NEW</span>
          </a>
          <ul class="pcoded-submenu">
            <li class=" pcoded-hasmenu">
              <a href="javascript:void(0)" class="waves-effect waves-dark">
                <span class="pcoded-mtext">Listar clientes</span>
              </a>
              <ul class="pcoded-submenu">
                <li class="">
                  <a href="menu-static.html" class="waves-effect waves-dark">
                    <span class="pcoded-mtext">Static Layout</span>
                  </a>
                </li>
                <li class="">
                  <a href="menu-header-fixed.html" class="waves-effect waves-dark">
                   <span class="pcoded-mtext">Header Fixed</span>
                  </a>
                </li>
                <li class="">
                  <a href="menu-compact.html" class="waves-effect waves-dark">
                    <span class="pcoded-mtext">Compact</span>
                  </a>
                </li>
                <li class="">
                  <a href="menu-sidebar.html" class="waves-effect waves-dark">
                    <span class="pcoded-mtext">Sidebar Fixed</span>
                  </a>
                </li> -->
              </ul>
            </li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title> <%= @title %> | Sistema MS </title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= favicon_link_tag 'favicon.ico' %>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Quicksand:500,700" rel="stylesheet">
    <!-- <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script> -->

    <%= stylesheet_link_tag    'application' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <% if logged_in? %>
      <%= render 'layouts/header'%>
                <div class="pcoded-content">
                  <%= yield %>
                </div>
              </div> <!-- pcoded-content -->
            </div> <!-- pcoded-wrapper -->
          </div> <!-- pcoded-main-container -->
        </div> <!-- pcoded-container navbar-wrapper -->
      </div> <!-- pcoded -->
    <% else %>
      <%= yield %>
    <% end %>
  </body>
</html>